- id: py-init-cleaner
  name: Python __init__.py Cleaner
  description: Pre-commit hook to clean up __init__.py files automatically.
  entry: py-init-cleaner
  language: rust
  types: [python]
  pass_filenames: false
  always_run: true
  args: ["--dir", "."]
