-   id: py-init-cleaner
    name: Python Init Cleaner
    description: Pre-commit hook to clean your python __init__.py files automatically
    entry: py-init-cleaner
    language: script
    types: [python]
    files: __init__\.py$
